### PR TITLE
Fix magic link issues

### LINKED ISSUE #23: Fix magic link issues
Currently, we've done a lot of things to integrate and make insights work with Magic Link but there are still some features & bugs we need to address. 
- [x] Metamask login is not working (See screenshot for error)
- [x] Currently some transactions are failing from time to time: make sure transactions are working
- [x] This is a weird issue 🤔 Magic transactions fail when a transaction is fired but the previous transaction popup is still displayed. If the popup is manually dismissed, the transactions go as expected but if the popup is not manually closed, the next transaction will fail (See attachments)
Screenshot 2023-10-31 at 14 57 37

### PR DESCRIPTION
**Pull request by tom1145**
Fixes [#23](https://github.com/oceanprotocol/insights/issues/23), [#26](https://github.com/oceanprotocol/insights/issues/26), [#25](https://github.com/oceanprotocol/insights/issues/25), [#29](https://github.com/oceanprotocol/insights/issues/29), [#30](https://github.com/oceanprotocol/insights/issues/30), [#24](https://github.com/oceanprotocol/insights/issues/24) .

Changes proposed in this PR:

- fix for metamask connection
- update network settings
- update page layout, cards, header, footer.

Screenshot 2023-11-15 at 17 03 48

### CODE REVIEW

File: src/components/custom/ConnectButton.tsx [hunk 1]
```diff
@@ -1,21 +1,18 @@
 // import { Button } from '@chakra-ui/react';
```
Comment (ionutiorgulescu) [inline src/components/custom/ConnectButton.tsx]: remove comment if is not used

File: src/components/custom/ReportSection/index.tsx [hunk 2]
```diff
@@ -5,90 +5,123 @@ import styles from './styles.module.scss';
...
+    initialStatesMessages['algoProcessingMessage' + dataItem.id] = '';
+    initialStatesImageProcessingDropdown['dropdown' + dataItem.id] =
+      ImageDataDropdown;
   });
-  initialStatesDropdownRealEstate['dropdown1'] = NrOfRoomsDataDropdown
-  initialStatesImageProcessingDropdown['dropdown1'] = ImageDataDropdown
-  const signer = useEthersSigner()
+  initialStatesDropdownRealEstate['dropdown1'] = NrOfRoomsDataDropdown;
+  initialStatesImageProcessingDropdown['dropdown1'] = ImageDataDropdown;
+  // const signer = useEthersSigner();
```
Comment (ionutiorgulescu) [inline src/components/custom/ReportSection/index.tsx]: remove comment if is not used

File: src/shared/utilities/wallet/index.ts [hunk 3]
```diff
@@ -1,95 +1,248 @@
...
-	],
+  // autoConnect: true,
+  publicClient,
+  webSocketPublicClient,
+  connectors: [
+    new UniversalWalletConnector({
+      chains,
+      options: {
+        // apiKey: "pk_live_0E5D589855DCF6D3",
+        apiKey: 'pk_live_D184E64BFC294E38',
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: should come from config?

File: src/shared/utilities/wallet/index.ts [hunk 4]
```diff
@@ -1,95 +1,248 @@
...
+          },
+          extensions: true,
+        },
+      },
+    }) as unknown as Connector,
+    new MagicWalletConnector({
+      chains,
+      options: {
+        // apiKey: "pk_live_0E5D589855DCF6D3",
+        apiKey: 'pk_live_D184E64BFC294E38',
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: should come from config?

File: src/shared/utilities/wallet/index.ts [hunk 5]
```diff
@@ -1,95 +1,248 @@
...
+  Connector,
+  configureChains,
+  createConfig,
+  erc20ABI,
+  Chain,
+  ConnectorData,
+} from 'wagmi';
+import { mainnet, polygon, polygonMumbai, sepolia } from 'wagmi/chains';
+import { publicProvider } from 'wagmi/providers/public';
+import { ethers, Contract } from 'ethers';
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: is still used?

File: src/shared/@ocean/context/WalletContext.tsx [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+  createContext,
+  useCallback,
+  useContext,
+  useEffect,
+  useState,
+} from 'react';
+import Web3 from 'web3';
+import { magic } from '../../utilities/libs/magic';
+import { WalletInfo } from 'magic-sdk';
+import { Signer, ethers } from 'ethers';
```
Comment (ionutiorgulescu) [inline src/shared/@ocean/context/WalletContext.tsx:10]: maybe you can use only web3 here

File: src/shared/utilities/libs/magic.ts [hunk 7]
```diff
@@ -1,26 +1,18 @@
...
-			},
-		})
-	);
+  // We make sure that the window object is available
+  // Then we create a new instance of Magic using a publishable key
+  return (
+    typeof window !== 'undefined' &&
+    new Magic(key, {
+      network: {
+        rpcUrl: `https://sepolia.infura.io/v3/${config.oceanApp.infuraProjectId}`,
```
Comment (ionutiorgulescu) [inline src/shared/utilities/libs/magic.ts]: you can take rpcUrl from config

File: src/shared/utilities/wallet/index.ts [hunk 8]
```diff
@@ -1,95 +1,244 @@
...
+
+  readonly isModalOpen = false;
+
+  provider?: UniversalWalletConnector;
+
+  constructor(config: {
+    chains;
+    options: {
+      // apiKey: "pk_live_0E5D589855DCF6D3",
+      apiKey: 'pk_live_D184E64BFC294E38';
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: can you take this from config?

File: src/shared/utilities/wallet/index.ts [hunk 9]
```diff
@@ -1,95 +1,244 @@
...
+          rpcUrl: 'https://polygon-rpc.com';
+          chainId: 137;
+        },
+        {
+          rpcUrl: 'https://rpc-mumbai.maticvigil.com';
+          chainId: 80001;
+        },
+        {
+          // rpcUrl: `https://sepolia.infura.io/v3/${process.env.NEXT_PUBLIC_INFURA_PROJECT_ID}`;
+          rpcUrl: `https://sepolia.infura.io/v3/853bee732cdf4e4383f88047e46ea89d`;
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: can you take this from config?

File: src/shared/utilities/wallet/index.ts [hunk 10]
```diff
@@ -1,95 +1,244 @@
...
+          chainId: 11155111;
+        }
+      ];
+      magicSdkConfiguration: {
+        network: {
+          // rpcUrl: `https://sepolia.infura.io/v3/${process.env.NEXT_PUBLIC_INFURA_PROJECT_ID}`;
+          rpcUrl: `https://sepolia.infura.io/v3/853bee732cdf4e4383f88047e46ea89d`;
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: can you take this from config?

File: src/shared/utilities/wallet/index.ts [hunk 11]
```diff
@@ -1,95 +1,244 @@
...
+            chainId: 80001,
+          },
+          {
+            rpcUrl: `https://sepolia.infura.io/v3/853bee732cdf4e4383f88047e46ea89d`,
+            chainId: 11155111,
+          },
+        ],
+        magicSdkConfiguration: {
+          network: {
+            rpcUrl: `https://sepolia.infura.io/v3/853bee732cdf4e4383f88047e46ea89d`,
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: can you take this from config?

File: src/shared/utilities/wallet/index.ts [hunk 12]
```diff
@@ -1,95 +1,244 @@
...
+          {
+            rpcUrl: 'https://polygon-rpc.com',
+            chainId: 137,
+          },
+          {
+            rpcUrl: 'https://rpc-mumbai.maticvigil.com',
+            chainId: 80001,
+          },
+          {
+            rpcUrl: `https://sepolia.infura.io/v3/853bee732cdf4e4383f88047e46ea89d`,
```
Comment (ionutiorgulescu) [inline src/shared/utilities/wallet/index.ts]: same

**Review by ionutiorgulescu — APPROVED** [review]
